### ISSUE TITLE
Pick java webserver

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/xenon-cwl#16]

**Comment by jmaassen** [comment]
The swagger generator in:

https://github.com/swagger-api/swagger-codegen

seems to have a list of supported frameworks? These are:

MSF4J, Spring, Undertow, JAX-RS: CDI, CXF, Inflector, RestEasy

**Comment by nielsdrost** [comment]
This seems promising: https://projects.spring.io/spring-boot/

As used in https://github.com/maartenplieger/adaguc-services/

**Comment by sverhoeven** [comment]
To generate server from swagger spec I would use the JAX-RS framework (-l jaxrs). 
As JAX-RS is the standard way to map java methods to urls. The generated code uses the Jetty web server.

**Comment by bpmweel** [comment]
For now we chose spring-boot for the first implementation.
