### ISSUE TITLE
Configure Xenon hosts

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/xenon-cwl#2]
Configure the hosts in a separate file, then choose the host we want to use

**Comment by bpmweel** [comment]
Configuration can be done through a yaml file.

It allows configuration of the xenon host (called ComputeResource), the default host and a sourceFileSystem (a xenon FileSystem).

Before execution files are staged from the sourceFileSystem to the hostFileSystem.
After execution results are staged back. Destination folder cannot be configured currently.
